// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using LearnWf.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace LearnWf.Models
{
    public partial class AdventureWorks2012Context
    {
        private IAdventureWorks2012ContextProcedures _procedures;

        public virtual IAdventureWorks2012ContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new AdventureWorks2012ContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IAdventureWorks2012ContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class AdventureWorks2012ContextProcedures : IAdventureWorks2012ContextProcedures
    {
        private readonly AdventureWorks2012Context _context;

        public AdventureWorks2012ContextProcedures(AdventureWorks2012Context context)
        {
            _context = context;
        }

        public virtual async Task<int> uspUpdateEmployeeHireInfoAsync(int? businessEntityID, string jobTitle, DateTime? hireDate, DateTime? rateChangeDate, decimal? rate, byte? payFrequency, bool? currentFlag, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "BusinessEntityID",
                    Value = businessEntityID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "JobTitle",
                    Size = 100,
                    Value = jobTitle ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "HireDate",
                    Value = hireDate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime,
                },
                new SqlParameter
                {
                    ParameterName = "RateChangeDate",
                    Value = rateChangeDate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime,
                },
                new SqlParameter
                {
                    ParameterName = "Rate",
                    Precision = 19,
                    Scale = 4,
                    Value = rate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Money,
                },
                new SqlParameter
                {
                    ParameterName = "PayFrequency",
                    Value = payFrequency ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.TinyInt,
                },
                new SqlParameter
                {
                    ParameterName = "CurrentFlag",
                    Value = currentFlag ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [HumanResources].[uspUpdateEmployeeHireInfo] @BusinessEntityID = @BusinessEntityID, @JobTitle = @JobTitle, @HireDate = @HireDate, @RateChangeDate = @RateChangeDate, @Rate = @Rate, @PayFrequency = @PayFrequency, @CurrentFlag = @CurrentFlag", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> uspUpdateEmployeeLoginAsync(int? businessEntityID, byte[] organizationNode, string loginID, string jobTitle, DateTime? hireDate, bool? currentFlag, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "BusinessEntityID",
                    Value = businessEntityID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "OrganizationNode",
                    Value = organizationNode ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Udt,
                    UdtTypeName = "hierarchyid",
                },
                new SqlParameter
                {
                    ParameterName = "LoginID",
                    Size = 512,
                    Value = loginID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "JobTitle",
                    Size = 100,
                    Value = jobTitle ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "HireDate",
                    Value = hireDate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime,
                },
                new SqlParameter
                {
                    ParameterName = "CurrentFlag",
                    Value = currentFlag ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [HumanResources].[uspUpdateEmployeeLogin] @BusinessEntityID = @BusinessEntityID, @OrganizationNode = @OrganizationNode, @LoginID = @LoginID, @JobTitle = @JobTitle, @HireDate = @HireDate, @CurrentFlag = @CurrentFlag", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> uspUpdateEmployeePersonalInfoAsync(int? businessEntityID, string nationalIDNumber, DateTime? birthDate, string maritalStatus, string gender, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "BusinessEntityID",
                    Value = businessEntityID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "NationalIDNumber",
                    Size = 30,
                    Value = nationalIDNumber ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "BirthDate",
                    Value = birthDate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime,
                },
                new SqlParameter
                {
                    ParameterName = "MaritalStatus",
                    Size = 2,
                    Value = maritalStatus ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NChar,
                },
                new SqlParameter
                {
                    ParameterName = "Gender",
                    Size = 2,
                    Value = gender ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [HumanResources].[uspUpdateEmployeePersonalInfo] @BusinessEntityID = @BusinessEntityID, @NationalIDNumber = @NationalIDNumber, @BirthDate = @BirthDate, @MaritalStatus = @MaritalStatus, @Gender = @Gender", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
